name: End-to-End Tests Playwright

on:
    pull_request:
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * *'
    push:

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    e2e-record:
        name: E2E Tests (record)
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

            - name: Use desired version of NodeJS
              uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # v3.1.0
              with:
                  node-version-file: '.nvmrc'
                  cache: npm

            - name: Npm install and build
              run: |
                  npm ci
                  npm run build

            - name: Install WordPress and start the server
              run: |
                  npm run wp-env start

            - name: Run the tests
              run: |
                  npm run test:e2e:playwright:replay

            - name: Upload replays
              if: ${{ always() }}
              uses: replayio/action-upload@v0.4.5
              with:
                  api-key: rwk_yQySnIuU2WPV8LrmwIeWiaQNR5OS4Fi25hOeMDf7gRI
                  filter: ${{ 'function($v) { $v.metadata.test.result = "failed" }' }}
    e2e-no-record:
        name: E2E Tests (no record)
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

            - name: Use desired version of NodeJS
              uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # v3.1.0
              with:
                  node-version-file: '.nvmrc'
                  cache: npm

            - name: Npm install and build
              run: |
                  npm ci
                  npm run build

            - name: Install WordPress and start the server
              run: |
                  npm run wp-env start

            - name: Run the tests
              run: |
                  npm run test:e2e:playwright:replay
              env:
                  RECORD_REPLAY_TEST_METRICS: 1
                  RECORD_REPLAY_WEBHOOK_URL: ${{ secrets.RECORD_REPLAY_WEBHOOK_URL }}
                  RECORD_REPLAY_NO_RECORD: 1
    original:
        name: E2E Tests
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

            - name: Use desired version of NodeJS
              uses: actions/setup-node@5b52f097d36d4b0b2f94ed6de710023fbb8b2236 # v3.1.0
              with:
                  node-version-file: '.nvmrc'
                  cache: npm

            - name: Npm install and build
              run: |
                  npm ci
                  npm run build

            - name: Install Playwright dependencies
              run: |
                  npx playwright install chromium --with-deps

            - name: Install WordPress and start the server
              run: |
                  npm run wp-env start

            - name: Run the tests
              run: |
                  npm run test:e2e:playwright

            - name: Archive debug artifacts (screenshots, traces)
              uses: actions/upload-artifact@e448a9b857ee2131e752b06002bf0e093c65e571 # v2.2.2
              if: always()
              with:
                  name: failures-artifacts
                  path: artifacts
                  if-no-files-found: ignore

            - name: Archive flaky tests report
              uses: actions/upload-artifact@e448a9b857ee2131e752b06002bf0e093c65e571 # v2.2.2
              if: always()
              with:
                  name: flaky-tests-report-playwright
                  path: flaky-tests
                  if-no-files-found: ignore
